---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "{{ kubernetes_control_plane_lib_location_ca }}"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "10.32.0.10"
podCIDR: "10.200.{{ worker_node_index }}.0/24"
resolvConf: "/run/systemd/resolve/resolv.conf"
runtimeRequestTimeout: "15m"
tlsCertFile: "{{ worker_kubelet_lib_location }}/{{ inventory_hostname }}.pem"
tlsPrivateKeyFile: "{{ worker_kubelet_lib_location }}/{{ inventory_hostname }}-key.pem"
