---
- name: Ensure kubernetes config and cert dirs
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ certificates_client_server_kube_proxy_client_location }}'

- name: Create kube proxy client json configuration files for cfssl
  template:
    src: '{{ item.src }}'
    dest: '{{ certificates_client_server_kube_proxy_client_location }}/{{ item.dest }}'
  with_items: 
    - { src: 'csr.json', dest: 'kube-proxy-csr.json', cn: 'system:kube-proxy'}
  register: proxy_cert_info

- name: Generate kube proxy client certificates
  shell: |
    cfssl gencert \
      -ca={{ certificates_ca_location }}/ca.pem \
      -ca-key={{ certificates_ca_location }}/ca-key.pem \
      -config={{ certificates_ca_location }}/ca-config.json \
      -profile=kubernetes \
      kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: '{{ certificates_client_server_kube_proxy_client_location }}'
  when: proxy_cert_info is changed