---
- name: Ensure control plane dirs
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ kubernetes_control_plane_config_location }}'
    - '{{ kubernetes_control_plane_lib_location }}'

- import_tasks: binaries.yml
- import_tasks: api_server.configure.yml
- import_tasks: api_server.service.yml
- import_tasks: controller_manager.configure.yml
- import_tasks: controller_manager.service.yml
- import_tasks: scheduler.configure.yml
- import_tasks: scheduler.service.yml

- name: Wait until kubernetes api server is up
  uri:
    url: "https://192.168.50.100:6443/healthz"
    validate_certs: no
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
